// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjteavcsofnsusyviciz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqdGVhdmNzb2Zuc3VzeXZpY2l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2MDc4NTUsImV4cCI6MjA3NzE4Mzg1NX0.p-Q7XMWWDls-Ugh7_vRUnja5umiWPUfl11wcCFeDYYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});